#include <opencv2/opencv.hpp>
#include <zmq.hpp>
#include <fcntl.h>
#include <sys/mman.h>
#include <semaphore.h>
#include <unistd.h>
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <cstring>


struct DetectionResult {   // Recieves from Slow Algorithm
    bool valid;
    float confidence;
    cv::Point2f corners[4];
    long long timestamp_ms; 
};

struct OverlayData {   // Sends to Video Player
    bool valid;
    float distance;
    float position[3];
    float orientation[3];
    float confidence;
    cv::Point2f corners[4];
};

struct TrackingStatusMsg {  // Sends to Slow Algorithm
    bool request_detection;
    int active_points;
    float last_confidence;
    long long timestamp_ms; 
};

int main() {
    cv::Mat camera_matrix, dist_coeffs;
    cv::FileStorage fs("/mnt/c/Users/dinay/ComputerVisionAssignment/Camera_Calibration/calibration.yaml", cv::FileStorage::READ);
    if (!fs.isOpened()) return -1;
    fs["Camera_Matrix"] >> camera_matrix;
    fs["Distortion_Coefficients"] >> dist_coeffs;
    fs.release();

    const float A4_Width = 0.210f;
    const float A4_Height = 0.297f;
    std::vector<cv::Point3f> obj_points = { // (0,0,0) is the center of A4 page
        {-A4_Width / 2, -A4_Height / 2, 0}, { A4_Width / 2, -A4_Height / 2, 0},
        { A4_Width / 2,  A4_Height / 2, 0}, {-A4_Width / 2,  A4_Height / 2, 0}
    }; 

    zmq::context_t context(1);
    zmq::socket_t frame_transmit(context, ZMQ_PULL);
    frame_transmit.connect("tcp://127.0.0.1:5555");
    
    zmq::socket_t overlay_tx(context, ZMQ_PUSH);
    overlay_tx.connect("tcp://127.0.0.1:5556");

    zmq::socket_t slow_trigger_tx(context, ZMQ_PUSH);
    slow_trigger_tx.bind("tcp://127.0.0.1:5557");
    
    zmq::socket_t slow_result_rx(context, ZMQ_PULL);
    slow_result_rx.bind("tcp://127.0.0.1:5558");

    const int width = 1080;
    const int height = 1920;
    const int channels = 3;
    const int frame_size = width * height * channels;

    // Open existing POSIX shared memory and semaphore
    int shm_fd = shm_open("/DroneFrameMemory", O_RDONLY, 0666);
    if (shm_fd == -1) {
        std::cerr << "Fast Algorithm: Failed to open shared memory." << std::endl;
        return -1;
    }
    void* shm_ptr = mmap(NULL, frame_size, PROT_READ, MAP_SHARED, shm_fd, 0);
    
    sem_t* mutex_sem = sem_open("/DroneFrameMutex", 0);
    if (mutex_sem == SEM_FAILED) {
        std::cerr << "Fast Algorithm: Failed to open semaphore." << std::endl;
        return -1;
    }

    bool tracking = false;
    float current_confidence = 0.0f;
    cv::Mat prev_gray;
    std::vector<cv::Point2f> tracked_corners;
    std::vector<cv::Point2f> new_corners;

    std::cout << "Fast Algorithm running and ready." << std::endl;
    std::ofstream log_file("performance_log.csv");
    log_file << "Timestamp_ms,Confidence,Reprojection_Error,Tracking_Valid\n";

    while (true) {
        zmq::message_t trigger_msg;
        (void)frame_transmit.recv(trigger_msg, zmq::recv_flags::none);

        // extract the exact timestamp generated by the Video Player
        long long current_frame_timestamp = *static_cast<long long*>(trigger_msg.data());

        // Lock, read from POSIX mapping, unlock
        sem_wait(mutex_sem);
        cv::Mat shared_frame(height, width, CV_8UC3, shm_ptr);
        cv::Mat gray;
        cv::cvtColor(shared_frame, gray, cv::COLOR_BGR2GRAY); // src,dst convert the 3-color image for 1 color channel for opticalFlow algorithm
        sem_post(mutex_sem);

        OverlayData overlay_out = {0};
        int good_points = 0; 
        float reprojection_error = -1.0f; // intialize for csv file

        zmq::message_t result_msg;
        if (slow_result_rx.recv(result_msg, zmq::recv_flags::dontwait)) {
            DetectionResult* res = static_cast<DetectionResult*>(result_msg.data());
            if (res->valid && res->confidence > 0.5f) { // 50% 
                tracked_corners.assign(res->corners, res->corners + 4); // indexes 0-3
                current_confidence = res->confidence;
                tracking = true;
                prev_gray = cv::Mat(); // creates empty matrix for skip optical flow for one frame
            }
        }

        if (tracking == true && !prev_gray.empty()) {
            std::vector<uchar> status;  // 1 if found in new frame, 0 otherwise
            std::vector<float> err;
            cv::calcOpticalFlowPyrLK(prev_gray, gray, tracked_corners, new_corners, status, err);

            for (uchar s : status) if (s == 1) good_points++;
            if (good_points == 4) {
                tracked_corners = new_corners;
                double dynamic_area = cv::contourArea(tracked_corners);
                current_confidence = std::min(0.99, dynamic_area / (width * height) + 0.5);
                cv::Mat rvec, tvec;
                bool success = cv::solvePnP(obj_points, tracked_corners, camera_matrix, dist_coeffs, rvec, tvec);
                if (success == true) {

                    //  start of high reprojection error check
                    std::vector<cv::Point2f> projected_points;
                    cv::projectPoints(obj_points, rvec, tvec, camera_matrix, dist_coeffs, projected_points); 
                    float total_error = 0.0f;
                    for (int i = 0; i < 4; ++i) {
                        total_error += cv::norm(tracked_corners[i] - projected_points[i]);
                    }
                    reprojection_error = total_error / 4.0f; 
                    float dynamic_threshold = width * 0.0325f; // 3.25%          
                    if (reprojection_error > dynamic_threshold) { 
                        success = false; 
                        tracking = false;
                        std::cout << "Reprojection error = " << reprojection_error << std::endl;
                    }                 
                    // end of high reprojection error check

                    if (success == true) { 
                        overlay_out.valid = true;
                        overlay_out.confidence = current_confidence;
                        overlay_out.distance = cv::norm(tvec);
                        
                        overlay_out.position[0] = tvec.at<double>(0); // x
                        overlay_out.position[1] = tvec.at<double>(1); // y
                        overlay_out.position[2] = tvec.at<double>(2); // z

                        cv::Mat R;
                        cv::Rodrigues(rvec, R); // convert rvec to 3x3 Matrix

                        // 0: X up (less degrees) and down (more degrees) 1-Y around axis 2-Z tilting
                        double sy = sqrt(R.at<double>(0,0) * R.at<double>(0,0) +  R.at<double>(1,0) * R.at<double>(1,0)); // cos(pitch)
                        if (sy >= 1e-6) { // cos (pitch)>0 so its not 90 degrees. checking for not dividing by 0
                            overlay_out.orientation[0] = atan2(R.at<double>(2,1), R.at<double>(2,2)) * 180.0 / CV_PI; // pitch
                            overlay_out.orientation[1] = atan2(-R.at<double>(2,0), sy) * 180.0 / CV_PI;               // yaw
                            overlay_out.orientation[2] = atan2(R.at<double>(1,0), R.at<double>(0,0)) * 180.0 / CV_PI; // roll
                        } else { 
                            overlay_out.orientation[0] = atan2(-R.at<double>(1,2), R.at<double>(1,1)) * 180.0 / CV_PI; 
                            overlay_out.orientation[1] = atan2(-R.at<double>(2,0), sy) * 180.0 / CV_PI;
                            overlay_out.orientation[2] = 0;
                        }                      

                        // start of geometry checks
                        bool distance_reasonable = (overlay_out.distance > 0.2f && overlay_out.distance < 6.0f); // 0.2-6 meters
                        bool orientation_reasonable = (std::abs(overlay_out.orientation[0]) < 70.0 && 
                                                       std::abs(overlay_out.orientation[1]) < 70.0);                                    
                        if (distance_reasonable == false || orientation_reasonable == false) {
                            success = false;
                            tracking = false; 
                            overlay_out.valid = false;
                            std::cout << "Distance reasonable = " << distance_reasonable << "\n"
                                      << "Orientation reasonable = " << orientation_reasonable << "\n"
                                      << "Pitch degrees = " << overlay_out.orientation[0] << "\n"
                                      << "Yaw degrees = " << overlay_out.orientation[1] << std::endl;
                        }                    
                        // end of geometry checks

                        if (success == true) {
                            for (int i = 0; i < 4; ++i) overlay_out.corners[i] = tracked_corners[i];
                        }                           
                    }
                }   
            } else { 
                tracking = false; 
            }
        }
        prev_gray = gray.clone(); // prepare for next loop iteration
        
        // slow algorithm re-detection request
        if (tracking == false) {
            TrackingStatusMsg status_msg;
            status_msg.request_detection = true;
            status_msg.active_points = good_points;
            status_msg.last_confidence = current_confidence;
            status_msg.timestamp_ms = current_frame_timestamp;
            zmq::message_t req(sizeof(TrackingStatusMsg));
            std::memcpy(req.data(), &status_msg, sizeof(TrackingStatusMsg));
            slow_trigger_tx.send(req, zmq::send_flags::dontwait); 
        }

        zmq::message_t overlay_msg(sizeof(OverlayData));
        std::memcpy(overlay_msg.data(), &overlay_out, sizeof(OverlayData));
        overlay_tx.send(overlay_msg, zmq::send_flags::none);

        log_file << current_frame_timestamp << "," 
                 << current_confidence << "," 
                 << reprojection_error << "," 
                 << (tracking ? 1 : 0) << "\n";
    }
    return 0;
}